baseURL = "https://audycje.com.pl/"
languageCode = "pl"
title = "Fundacja Więcej Mądrości"
theme = "PaperMod"

[params]
    showReadingTime = true
    showBreadCrumbs = true
    showPostNavLInks = true
    showShareButtons = true

[params.homeInfoParams]
    Title= ""

[params.cover]
    linkFullImages = true
    
[[menu.main]]
    name = "YouTube"
    url = "https://www.youtube.com/@audycjecompl"
    weight = 1

[[menu.main]]
    name = "Apple Podcast"
    url = "https://podcasts.apple.com/us/podcast/fundacja-więcej-mądrości/id1759615186"
    weight = 2

[[menu.main]]
    name = "Spotify"
    url = "https://open.spotify.com/show/08FcBlirC3jK86DzNfVC83"
    weight = 3  

[[menu.main]]
    name = "Słowa Kluczowe"
    url = "/tags/"
    weight = 4

[[menu.main]]
    name = "Archiwum"
    url = "/archives/"
    weight = 5

[[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 6
